# Generated by Django 5.0.7 on 2024-07-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('date_published', models.DateField(auto_now_add=True)),
                ('number_of_pages', models.IntegerField(default=1)),
                ('number_of_chapters', models.IntegerField(default=1)),
            ],
        ),
    ]
