# Generated by Django 5.0.7 on 2024-08-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(default='default_book.png', upload_to='book_covers'),
        ),
    ]
