# Generated by Django 5.0.7 on 2024-08-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(default='book_covers/default_book.png', upload_to='book_covers'),
        ),
    ]
